CREATE USER chaming1
IDENTIFIED BY "1234"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

GRANT CONNECT TO chaming1;
GRANT RESOURCE TO chaming1;
GRANT DBA TO chaming1;
GRANT SESSION TO chaming1;
GRANT CREATE TABLE, CREATE SESSION TO chaming1;


select * from dba_sys_privs
where grantee='CHAMING1';